#!/usr/bin/env bash
#
# clone-repo:
#   clones a keybase repository to target.
#
# enironment variables:
#  INPUT_REPO  : required. git repository to copy from.
#  INPUT_TARGET: optional. target directory to copy to. empty for tmp.
#
set -eo pipefail
log(){ echo -e "[action] $*" >&2; }
die(){ log "$@"; exit 1; }

[ -n "$INPUT_REPO" ] || die "empty INPUT_REPO"

target="${INPUT_TARGET:-$(basename "$INPUT_REPO")}"
[ -e "$target" ] || mkdir -p "$target"
[ -d "$target" ] || die "Target ($target) must be a directory"

git clone --depth 1 "$INPUT_REPO" "$target"
chmod -R 777 "$target" # allow non-root user cleanup
echo "target=$target" >> "$GITHUB_OUTPUT"

